apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: caps-ai
type: Opaque
stringData:
  JWT_SECRET: "__JWT_SECRET__"
  OPENAI_API_KEY: "__OPENAI_API_KEY__"
  CLOUDINARY_CLOUD_NAME: "__CLOUDINARY_CLOUD_NAME__"
  CLOUDINARY_API_KEY: "__CLOUDINARY_API_KEY__"
  CLOUDINARY_API_SECRET: "__CLOUDINARY_API_SECRET__"
