apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-uploads
  namespace: caps-ai
spec:
  storageClassName: azurefile-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
