[mypy]
python_version = 3.11
warn_unreachable = True
warn_return_any = True
no_implicit_optional = True
check_untyped_defs = True
ignore_missing_imports = True
follow_imports = skip
pretty = True
show_error_codes = True
