apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: caps-ai
type: Opaque
stringData:
  JWT_SECRET: "VaD+yJVMqL9t7UTVzz6kZZnLfzE6yoBwRO3fhkEWau34nZwlO6HDTH4XfStJsQceuHVGNUQ19xgfJFGlahCA0vwMoSDAuyz5NemkpBKrzGLdc1CGnj9CgXFIqamWAKu2"
  OPENAI_API_KEY: ""
  CLOUDINARY_CLOUD_NAME: ""
  CLOUDINARY_API_KEY: ""
  CLOUDINARY_API_SECRET: ""

