from __future__ import annotations

from typing import Any

SUBMISSION_SCHEMA_VERSION = 1
EVALUATION_SCHEMA_VERSION = 1
AI_JOB_SCHEMA_VERSION = 1
AI_EVALUATION_RUN_SCHEMA_VERSION = 1
SCHEDULER_LOCK_SCHEMA_VERSION = 1
SETTINGS_SCHEMA_VERSION = 1
ADMIN_ACTION_REVIEW_SCHEMA_VERSION = 1
ANALYTICS_SNAPSHOT_SCHEMA_VERSION = 1
USER_SESSION_SCHEMA_VERSION = 1
NOTIFICATION_SCHEMA_VERSION = 1
AUDIT_LOG_SCHEMA_VERSION = 1
REVIEW_TICKET_SCHEMA_VERSION = 1
NOTICE_SCHEMA_VERSION = 1
ASSIGNMENT_SCHEMA_VERSION = 1
CLUB_EVENT_SCHEMA_VERSION = 1
CLUB_SCHEMA_VERSION = 1
EVENT_REGISTRATION_SCHEMA_VERSION = 1
CLUB_MEMBER_SCHEMA_VERSION = 1
CLUB_APPLICATION_SCHEMA_VERSION = 1
SIMILARITY_LOG_SCHEMA_VERSION = 1
GROUP_SCHEMA_VERSION = 1
SUBJECT_SCHEMA_VERSION = 1
STUDENT_SCHEMA_VERSION = 1
CLASS_SLOT_SCHEMA_VERSION = 1
COURSE_OFFERING_SCHEMA_VERSION = 1
ENROLLMENT_SCHEMA_VERSION = 1
ATTENDANCE_RECORD_SCHEMA_VERSION = 1
INTERNSHIP_SESSION_SCHEMA_VERSION = 1
FACULTY_SCHEMA_VERSION = 1
DEPARTMENT_SCHEMA_VERSION = 1
SPECIALIZATION_SCHEMA_VERSION = 1
BRANCH_SCHEMA_VERSION = 1
PROGRAM_SCHEMA_VERSION = 1
BATCH_SCHEMA_VERSION = 1
SEMESTER_SCHEMA_VERSION = 1
CLASS_SCHEMA_VERSION = 1
TIMETABLE_SCHEMA_VERSION = 1
TIMETABLE_SUBJECT_TEACHER_MAP_SCHEMA_VERSION = 1
USER_SCHEMA_VERSION = 1


def normalize_schema_version(raw_value: Any, *, default: int) -> int:
    try:
        parsed = int(raw_value)
    except (TypeError, ValueError):
        return default
    return parsed if parsed >= 1 else default
